export { authRoutes } from './auth.routes';
export { predictionRoutes } from './prediction.routes';
export { matchRoutes } from './match.routes';
export { chatRoutes } from './chat.routes';
export { waitlistRoutes } from './waitlist.routes';
export { streamRoutes } from './stream.routes';
export { streamWalletRoutes } from './stream-wallet.routes';
export { fanTokensRoutes } from './fan-tokens.routes';
export { followRoutes } from './follow.routes';
