import { createHmac, scrypt, timingSafeEqual } from 'crypto';
import { env } from '../../../infrastructure/config/environment';

const GATE_TTL_MS = 12 * 60 * 60 * 1000;
// Mirrors ScryptAccessCodeVerifier — hashes generated by
// scripts/gen-access-code-hash.js ("<saltHex>:<derivedKeyHex>").
const SCRYPT_PARAMS = { N: 16384, r: 8, p: 1 } as const;
const KEY_LEN = 64;

function sign(payload: string): string {
    return createHmac('sha256', env.JWT_SECRET).update(payload).digest('hex');
}

function deriveKey(code: string, salt: Buffer): Promise<Buffer> {
    return new Promise((resolve, reject) =>
        scrypt(code, salt, KEY_LEN, SCRYPT_PARAMS, (err, key) => (err ? reject(err) : resolve(key))),
    );
}

/** Scrypt code check — null when the gate is disabled (no hash configured). */
export async function verifyGateCode(code: string): Promise<boolean | null> {
    const stored = env.ADMIN_GATE_CODE_HASH;
    if (!stored) return null;
    const [saltHex, hashHex] = stored.split(':');
    if (!saltHex || !hashHex) return false;
    try {
        const derived = await deriveKey(code.trim(), Buffer.from(saltHex, 'hex'));
        const expected = Buffer.from(hashHex, 'hex');
        return derived.length === expected.length && timingSafeEqual(derived, expected);
    } catch {
        return false;
    }
}

/** HMAC gate token `expiry.signature` — stateless, bound to JWT_SECRET. */
export function issueGateToken(now: Date): string {
    const expiry = String(now.getTime() + GATE_TTL_MS);
    return `${expiry}.${sign(expiry)}`;
}

export function isGateTokenValid(token: string | undefined, now: Date): boolean {
    if (!env.ADMIN_GATE_CODE_HASH) return true; // gate disabled
    if (!token) return false;
    const [expiry, signature] = token.split('.');
    if (!expiry || !signature) return false;
    if (Number(expiry) < now.getTime()) return false;
    const expected = sign(expiry);
    const a = Buffer.from(signature);
    const b = Buffer.from(expected);
    return a.length === b.length && timingSafeEqual(a, b);
}
